---
title: "README"
author: "K Todd-Brown (ktoddbrown@gmail.com); D LeBauer (dlebauer@gmail.com)"
date: "April 29, 2015"
output: 
  html_document: 
    toc: yes
---

This is the main public repository for a meta-data study collecting data sets related to soil and litter decompositon. Each study has it's own folder which will include:

* `README.txt` - meta-information on the study including links to archive repository, links to manuscripts associated with the original publication, contact for the study (if applicable), and other comments.
* `author_YYYY_datatype/` directories contain data files in their original format
* `processData.Rmd` - an Rmarkdown document which processes the orginal data files into 4 long format csv files (`outputs/processedType.csv`) with the specifications outlined below and includes basic visualizations.

Note that we have chosen to exclude priming experiments for the purposes of this study.

The respective csv columns will contain at most the following columns:

### `ProcessedData.csv`
Primary data set for decomposition model including time and stock/flux of carbon.

* study_id
* substrate_id
* environment_id
* group_id # suggested grouping for modeling study
* elapsed_time # days since initiation
* time_unit # should be day, included so that the data set can be used without reference
* carbon_flux # (g CO2-C / g soil-C_inital / d) for soil core incubations; NA otherwise
* carbon_stock # (g C / g C_inital) for litterbag studies; NA otherwise
* carbon_unit # included so that the data set can be used without reference

### `ProcessedEnvironmental.csv`
This should describe the enviroment that the sample was incubated in, not the location which generated the sample. Data set for enviromental sensitivity of model-data integration. 

* environmental_id
* percent_water # saturation of soil core as a percent of field capasity
* temperature # (C) incubation temperature
* nutrient #Nutrient addition to sample during incubation
* MAP # (mm yr^-1) mean annual precipitation at litterbag site
* MAT # (C) mean annual temperature at litterbag site
* latitude # location of litterbag site
* longitude # location of litterbag site

### `ProcessedSubstrates.csv` (Initial Conditions)
This should describe the sample and conditions from the sampling site. Data set for enviromental sensitivity of model-data integration, also used to identify data grouping to fit different model parameters to. 

* substrate_id
* type # one of two options: soil or litterbag
* CO2 # CO2 enrichment at sample/study site
* percent_clay
* percent_lignin
* percent_carbon
* percent_nitrogen
* bulk_density # g cm^-3
* d13C
* depth_lower # lower sample depth in cm
* depth_upper # upper sample depth in cm
* latitude # location of soil core source site
* longitude # location of soil core source site
* plot # plot number from site if applicable

### `ProcessedStudy.csv`
Data set for study evaluation.

* study_id
* author # contact author for data set (or study)
* year # ending year of incubation or litter exposure
* url # url or DOI for data set; alternatively DOI for inital manuscript
* method # to measure carbon flux or carbon stock
* instrument # to measure carbon flux or carbon stock
* primary_citation #url (dx.doi.org prefered) of main citation to describe data collect
* volume # litter or soil volume used in study
