---
title: "Process data to long format"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "May 7, 2015"
output: html_document
---

```{r}
library(xlsx)
library(ggplot2)
library(reshape2)
```

```{r declareDF}
data.df <- data.frame()
environment.df <- data.frame()
substrate.df <- data.frame()
study.df <- data.frame()
```

```{r soilProperties}
soilProperty_meta <- read.xlsx(file='SICO2_FL_Soil_C_N_15N_mineral_CPOM_density_fractions.xlsx', sheetIndex=1)

cat(sprintf('Title: %s\nInvestigators: %s (contact), %s, %s,  %s, %s, %s, %s, %s, %s\nStudy period:%s -- %s\nSite: %s [%sN x %sW at %s meters]\nAbstract: %s\nMethod: %s\nAssociated publication: %s\n', soilProperty_meta[6,3], 
            soilProperty_meta[7,3], soilProperty_meta[7,4], soilProperty_meta[7,5], soilProperty_meta[7,6],soilProperty_meta[7,7], soilProperty_meta[8,3], soilProperty_meta[8,4],soilProperty_meta[8,5],soilProperty_meta[8,6],
            soilProperty_meta[10,3],soilProperty_meta[11,3],
            soilProperty_meta[12,3], soilProperty_meta[13,3], soilProperty_meta[14,3], soilProperty_meta[15,3],
            soilProperty_meta[18,3],
            soilProperty_meta[19,3],
            soilProperty_meta[25,3]))



study.df <- data.frame(author=soilProperty_meta[6,3],
                       url='ftp://cdiac.ornl.gov/pub/FACE/kscdata/Hungate/')

```

```{r getCper}
#soilProperty <- read.xlsx(file='SICO2_FL_Soil_C_N_15N_mineral_CPOM_density_fractions.xlsx', sheetIndex=5)
##Running into issues with the 'date' cell class so exported to csv as a quick fix
soilProperty <- read.csv(file='SICO2_FL_Soil_C_N_15N_mineral_CPOM_density_fractions_sheet5.csv', check.names=FALSE)
soilProperty <- soilProperty[1:361,c(1:4,6,10)]
names(soilProperty) <- c('date', 'plot', 'CO2_treatment', 'depth_cm', 'bulkDensity_g_cm3', 'perc_C')

soilProperty$depth_cm <- gsub('\\s*cm\\s*$', '', as.character(soilProperty$depth_cm))
cat(sprintf('Throwing out [%d] measurements due to non-numeric depths:\n', sum(!grepl('^\\s*\\d+-\\d+\\s*$', soilProperty$depth_cm))))
knitr::kable(soilProperty[!grepl('^\\s*\\d+-\\d+\\s*$', soilProperty$depth_cm),])
soilProperty <- soilProperty[grepl('^\\s*\\d+-\\d+\\s*$', soilProperty$depth_cm),]

cat(sprintf('Dropping [%d] entries due to missing C percentage:\n', sum(!grepl('^\\d+?\\.\\d*$', soilProperty$perc_C))))
knitr::kable(soilProperty[!grepl('^\\d+?\\.\\d*$', soilProperty$perc_C),])
soilProperty <- soilProperty[grepl('^\\d+?\\.\\d*$', soilProperty$perc_C),]

soilProperty$perc_C <- as.numeric(as.character(soilProperty$perc_C))
soilProperty$year <- as.numeric(substr(as.character(soilProperty$date), 5, 6))
soilProperty$year <- ifelse(soilProperty$year > 90, soilProperty$year + 1900, soilProperty$year + 2000)

depth.df <- as.data.frame(t(as.data.frame(strsplit(as.character(soilProperty$depth_cm), '-'))))
names(depth.df) <- c('min', 'max')
row.names(depth.df) <- NULL
soilProperty <- cbind(soilProperty, depth.df)
#soilProperty$newdepth <- sprintf('%03d-%03d', as.numeric(as.character(depth.df$min)), as.numeric(as.character(depth.df$max)))
soilProperty$meanDepth_cm <- (as.numeric(as.character(soilProperty$min)) + as.numeric(as.character(soilProperty$max)))/2

ggplot(data=soilProperty) + geom_point(aes(x=meanDepth_cm, y=bulkDensity_g_cm3, color=CO2_treatment)) + ylab('Bulk density [g cm^-3]')
ggplot(data=soilProperty) + geom_point(aes(x=meanDepth_cm, y=perc_C, color=CO2_treatment)) + ylab('Carbon percentage [%]')

ggplot(data=soilProperty) + geom_point(aes(x=meanDepth_cm, y=bulkDensity_g_cm3, color=year)) + ylab('Bulk density [g cm^-3]')
ggplot(data=soilProperty) + geom_point(aes(x=meanDepth_cm, y=perc_C, color=year)) + ylab('Carbon percentage [%]')

```
```{r readIncubation}
incubation_meta <- read.xlsx(file='SICO2_FL_soil_lab_incubations.xlsx', sheetIndex=1)

cat(sprintf('Title: %s\nInvestigators: %s (contact), %s, %s,  %s, %s, %s, %s, %s\nStudy period:%s -- %s\nSite: %s [%sN x %sW at %s meters]\nAbstract: %s\nMethod: %s\nAssociated publication: %s\n', incubation_meta[6,3], 
            incubation_meta[7,3], incubation_meta[7,4], incubation_meta[7,5], incubation_meta[7,6],incubation_meta[7,7], incubation_meta[8,3], incubation_meta[8,4],incubation_meta[8,5],
            incubation_meta[10,3],incubation_meta[11,3],
            incubation_meta[12,3], incubation_meta[13,3], incubation_meta[14,3], incubation_meta[15,3],
            incubation_meta[18,3],
            incubation_meta[19,3],
            incubation_meta[25,3]))
cat('Soil carbon in active, slow, and resistant fractions (ugC/g soil), and their sum (total). Active and slow calculated from CO2 production during long-term lab incubations. Resistant estimated as organic C remaining after acid hydrolysis. Also shown are rates of CO2 production in the incubations, in units of ugC/g soil/d\n')
incubation_2002 <- read.xlsx(file='SICO2_FL_soil_lab_incubations.xlsx', sheetIndex=2, startRow=7)
incubation_2002 <- incubation_2002[1:48,c(1:4, 11:16)]
names(incubation_2002) <- c('date', 'plot', 'CO2_treatment', 'depth_cm', 'day_1', 'day_15', 'day_28', 'day_66', 'day_140', 'day_256')
incubation_2002$collection_year <- as.numeric(substr(as.character(incubation_2002$date), 1,4))
incubation_2002$depth_cm <- gsub(' cm', '', as.character(incubation_2002$depth_cm))

incubation_2002 <- melt(incubation_2002, id.vars = c('date', 'plot', 'CO2_treatment', 'depth_cm', 'collection_year'))
incubation_2002$value <- as.numeric(incubation_2002$value)
incubation_2002$variable <- as.numeric(gsub('day_', '', incubation_2002$variable))
names(incubation_2002)[c(1,6:7)] <- c('collection_date', 'incubation_day', 'dCO2')
incubation_2002$units <- 'ug-C g^-1-soil d^-1'
incubation_2002$collection_date <- NULL

depth.df <- as.data.frame(t(as.data.frame(strsplit(incubation_2002$depth_cm, '-'))))
names(depth.df) <- c('min', 'max')
row.names(depth.df) <- NULL
#incubation$newdepth <- sprintf('%03d-%03d', as.numeric(as.character(depth.df$min)), as.numeric(as.character(depth.df$max)))
incubation_2002$meanDepth_cm <- (as.numeric(as.character(depth.df$min)) + as.numeric(as.character(depth.df$max)))/2

ggplot(incubation_2002) + geom_point(aes(x=incubation_day, y=dCO2, color=CO2_treatment), alpha=0.5)+scale_x_log10()

incubation_2007 <- read.xlsx(file='SICO2_FL_soil_lab_incubations.xlsx', sheetIndex=3, startRow=10)
incubation_2007 <- incubation_2007[,1:16]
names(incubation_2007) <- c('date', 'plot', 'depth_cm', 'depth_code', 'nutrient', 'CO2_treatment', 'day_1', 'day_5', 'day_16', 'day_37', 'day_65', 'day_108', 'day_163', 'day_219', 'day_335', 'day_542')
incubation_2007$collection_year <- as.numeric(substr(as.character(incubation_2007$date), 1,4))
incubation_2007$depth_cm <- gsub('cm$', '', as.character(incubation_2007$depth_cm))

incubation_2007 <- melt(incubation_2007, id.vars = c('date', 'collection_year', 'plot', 'depth_code', 'nutrient',  'CO2_treatment', 'depth_cm'))
incubation_2007$value <- as.numeric(incubation_2007$value)
incubation_2007$variable <- as.numeric(gsub('day_', '', incubation_2007$variable))
names(incubation_2007)[c(1,8:9)] <- c('collection_date', 'incubation_day', 'dCO2')
incubation_2007$units <- 'ug-C g^-1-soil d^-1'
incubation_2007$collection_date <- NULL

depth.df <- as.data.frame(t(as.data.frame(strsplit(incubation_2007$depth_cm, '-'))))
names(depth.df) <- c('min', 'max')
row.names(depth.df) <- NULL
#incubation$newdepth <- sprintf('%03d-%03d', as.numeric(as.character(depth.df$min)), as.numeric(as.character(depth.df$max)))
incubation_2007$meanDepth_cm <- (as.numeric(as.character(depth.df$min)) + as.numeric(as.character(depth.df$max)))/2

ggplot(incubation_2007) + geom_point(aes(x=incubation_day, y=dCO2, color=CO2_treatment), alpha=0.5)+scale_x_log10()

incubation <- merge(incubation_2007, incubation_2002, all=TRUE)
names(incubation)[1] <- 'year'
incubation$CO2_treatment <- factor(substr(as.character(incubation$CO2_treatment), 1,1))
```

```{r pullData}

incubationOfInterest <- incubation[,c('year', 'CO2_treatment', 'plot', 'meanDepth_cm', 'nutrient', 'incubation_day', 'dCO2')]
incubationOfInterest$caseID <- sprintf('%s_%s_%s_%s_%s', incubationOfInterest$year, incubationOfInterest$CO2_treatment, incubationOfInterest$meanDepth_cm, incubationOfInterest$nutrient, incubationOfInterest$plot)
#incubationOfInterest <- incubationOfInterest[incubationOfInterest$caseID==incubationOfInterest$caseID[1],]

soilPropertiesOfInterest <- soilProperty[,c('year', 'CO2_treatment', 'plot', 'meanDepth_cm', 'perc_C')]
soilPropertiesOfInterest$caseID <- sprintf('%s_%s_%s_%s', soilPropertiesOfInterest$year, soilPropertiesOfInterest$CO2_treatment, soilPropertiesOfInterest$meanDepth_cm, soilPropertiesOfInterest$plot)
#soilPropertiesOfInterest <- soilPropertiesOfInterest[soilPropertiesOfInterest$caseID %in% '2002_A_5_1',]

data <- merge(incubationOfInterest, soilPropertiesOfInterest, by=c('year', 'CO2_treatment', 'plot', 'meanDepth_cm'), suffixes = c('incubation', 'property'))
data$dCO2 <- data$dCO2*(100/data$perc_C)*1e-6
data$units <- 'g-C-C02*g^-1-C-initSoil*d^-1'
data$perc_C <- NULL

data$caseID <- sprintf('%s_%s_%s_%s_%s', data$year, data$CO2_treatment, data$meanDepth, data$nutrient, data$plot)
ggplot(data[data$year == 2002,]) + geom_line(aes(x=incubation_day, y=dCO2, group=caseID), alpha=0.5) +scale_x_log10()
ggplot(data[data$year == 2007,]) + geom_line(aes(x=incubation_day, y=dCO2, group=caseID), alpha=0.5) +scale_x_log10()
```